on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      KP_USER: ${{ secrets.KP_USER }}
      KP_PW: ${{ secrets.KP_PW }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
          r-version: 4.1.3
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            pkgdown
            animation
            baseballr
            cfbfastR
            chessR
            fastRhockey
            ggimage
            knitr
            pacman
            ragg
            rsconnect
            tictoc
            tidyverse
            toRvik
            wehoop
            zoo
          needs: website
      - name: Install system dependencies
        run: |
          pak::pkg_install("hadley/emo")
          pak::pkg_install("r-lib/pkgapi")
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
